# Welcome to Jekyll!
# vim: set ts=2 sw=2
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PyCon Québec
#email: pycon.qc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tout ce que vous devez savoir sur PyCon Québec | All you need to know about PyCon Québec. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pycon.quebec" # the base hostname & protocol for your site
#twitter_username: pyconqc
#github_username:  pyconqc

# Build settings
markdown: kramdown
exclude:
  - scripts
  - README.md
  - LICENSE
